services:
  postgresdb:
    image: postgres:15
    restart: unless-stopped
    env_file: ../.env
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - shared_net

volumes:
  pgdata:

networks:
  shared_net:
    name: shared_net
    driver: bridge
