services:
  redis:
    image: redis:latest
    restart: always
    command: ["redis-server", "--bind", "redis", "--port", "6379", "--requirepass", "${REDIS_PASSWORD}"]
    env_file: ../.env
    environment:
        REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    networks:
      - shared_net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 20s
      retries: 5
      start_period: 5s

networks:
  shared_net:
    name: shared_net
    driver: bridge
